INSERT INTO enterprise(enterprise_id,name) VALUES (1,'네이버(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (2,'카카오(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (3,'(주)다우기술');
INSERT INTO enterprise(enterprise_id,name) VALUES (4,'(주)빗썸홀딩스');
INSERT INTO enterprise(enterprise_id,name) VALUES (5,'(주)케이티씨에스');
INSERT INTO enterprise(enterprise_id,name) VALUES (6,'메가존(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (7,'네이버클라우드(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (8,'라인플러스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (9,'엔에이치엔한국사이버결제(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (10,'(주)카카오모빌리티');
INSERT INTO enterprise(enterprise_id,name) VALUES (11,'나이스평가정보(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (12,'(주)야놀자');
INSERT INTO enterprise(enterprise_id,name) VALUES (13,'(주)코스콤');
INSERT INTO enterprise(enterprise_id,name) VALUES (14,'네이버웹툰(유)');
INSERT INTO enterprise(enterprise_id,name) VALUES (15,'(주)케이지모빌리언스');
INSERT INTO enterprise(enterprise_id,name) VALUES (16,'구글코리아(유)');
INSERT INTO enterprise(enterprise_id,name) VALUES (17,'(주)연합뉴스');
INSERT INTO enterprise(enterprise_id,name) VALUES (18,'이데일리(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (19,'(주)여기어때컴퍼니');
INSERT INTO enterprise(enterprise_id,name) VALUES (20,'카페24(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (21,'(주)드림어스컴퍼니');
INSERT INTO enterprise(enterprise_id,name) VALUES (22,'(주)헥토이노베이션');
INSERT INTO enterprise(enterprise_id,name) VALUES (23,'(주)가비아');
INSERT INTO enterprise(enterprise_id,name) VALUES (24,'한국인터넷진흥원');
INSERT INTO enterprise(enterprise_id,name) VALUES (25,'(주)브랜드엑스코퍼레이션');
INSERT INTO enterprise(enterprise_id,name) VALUES (26,'(주)이엔코퍼레이션');
INSERT INTO enterprise(enterprise_id,name) VALUES (27,'(주)와이지플러스');
INSERT INTO enterprise(enterprise_id,name) VALUES (28,'(주)이머니');
INSERT INTO enterprise(enterprise_id,name) VALUES (29,'인포뱅크(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (30,'(주)에스비에스에이앤티');
INSERT INTO enterprise(enterprise_id,name) VALUES (31,'(주)사람인에이치알');
INSERT INTO enterprise(enterprise_id,name) VALUES (32,'한일네트웍스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (33,'(주)키다리스튜디오');
INSERT INTO enterprise(enterprise_id,name) VALUES (34,'한국평가데이터(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (35,'(주)헥토파이낸셜');
INSERT INTO enterprise(enterprise_id,name) VALUES (36,'(주)알스퀘어');
INSERT INTO enterprise(enterprise_id,name) VALUES (37,'블룸버그코리아(유)');
INSERT INTO enterprise(enterprise_id,name) VALUES (38,'(주)더플랜코퍼레이션');
INSERT INTO enterprise(enterprise_id,name) VALUES (39,'(주)천재교육');
INSERT INTO enterprise(enterprise_id,name) VALUES (40,'GS건설(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (41,'유빈스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (42,'(주)예가람저축은행');
INSERT INTO enterprise(enterprise_id,name) VALUES (43,'(주)코리아써키트');
INSERT INTO enterprise(enterprise_id,name) VALUES (44,'(주)하나금융티아이');
INSERT INTO enterprise(enterprise_id,name) VALUES (45,'현대건설');
INSERT INTO enterprise(enterprise_id,name) VALUES (46,'(주)현대홈쇼핑');
INSERT INTO enterprise(enterprise_id,name) VALUES (47,'롯데캐피탈(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (48,'KB생명보험(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (49,'제일약품');
INSERT INTO enterprise(enterprise_id,name) VALUES (50,'현대오토에버(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (51,'금호건설(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (52,'한국투자증권(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (53,'대상정보기술(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (54,'GS네오텍(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (55,'(주)플그림');
INSERT INTO enterprise(enterprise_id,name) VALUES (56,'쿠팡 주식회사');
INSERT INTO enterprise(enterprise_id,name) VALUES (57,'롯데멤버스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (58,'브이피(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (59,'플레이디');
INSERT INTO enterprise(enterprise_id,name) VALUES (60,'한화테크윈(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (61,'삼성물산');
INSERT INTO enterprise(enterprise_id,name) VALUES (62,'(주)LF');
INSERT INTO enterprise(enterprise_id,name) VALUES (63,'(주)신세계아이앤씨');
INSERT INTO enterprise(enterprise_id,name) VALUES (64,'(주)포스코');
INSERT INTO enterprise(enterprise_id,name) VALUES (65,'교보핫트랙스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (66,'현대자동차(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (67,'(주)한샘');
INSERT INTO enterprise(enterprise_id,name) VALUES (68,'SM그룹');
INSERT INTO enterprise(enterprise_id,name) VALUES (69,'엠코테크놀로지');
INSERT INTO enterprise(enterprise_id,name) VALUES (70,'우리은행-우리에프아이에스');
INSERT INTO enterprise(enterprise_id,name) VALUES (71,'기업은행');
INSERT INTO enterprise(enterprise_id,name) VALUES (72,'KEB하나은행');
INSERT INTO enterprise(enterprise_id,name) VALUES (73,'SC제일은행');
INSERT INTO enterprise(enterprise_id,name) VALUES (74,'KB국민은행-KB데이터시스템');
INSERT INTO enterprise(enterprise_id,name) VALUES (75,'신한은행-신한DS');
INSERT INTO enterprise(enterprise_id,name) VALUES (76,'외환은행');
INSERT INTO enterprise(enterprise_id,name) VALUES (77,'한국시티은행');
INSERT INTO enterprise(enterprise_id,name) VALUES (78,'외환은행');
INSERT INTO enterprise(enterprise_id,name) VALUES (79,'카카오엔터프라이즈');
INSERT INTO enterprise(enterprise_id,name) VALUES (80,'LG CNS');
INSERT INTO enterprise(enterprise_id,name) VALUES (81,'삼성SDS');
INSERT INTO enterprise(enterprise_id,name) VALUES (82,'두산디지털이노베이션');
INSERT INTO enterprise(enterprise_id,name) VALUES (83,'SK C&C');
INSERT INTO enterprise(enterprise_id,name) VALUES (84,'CJ올리브네트웍스');
INSERT INTO enterprise(enterprise_id,name) VALUES (85,'티맥스소프트');
INSERT INTO enterprise(enterprise_id,name) VALUES (86,'현대IT&E');
INSERT INTO enterprise(enterprise_id,name) VALUES (87,'현대HDS');
INSERT INTO enterprise(enterprise_id,name) VALUES (88,'농협정보시스템');
INSERT INTO enterprise(enterprise_id,name) VALUES (89,'미라콤아이앤씨');
INSERT INTO enterprise(enterprise_id,name) VALUES (90,'IBK시스템');
INSERT INTO enterprise(enterprise_id,name) VALUES (91,'코오롱베니트');
INSERT INTO enterprise(enterprise_id,name) VALUES (92,'한화시스템/ICT');
INSERT INTO enterprise(enterprise_id,name) VALUES (93,'교보정보통신');
INSERT INTO enterprise(enterprise_id,name) VALUES (94,'KT DS');
INSERT INTO enterprise(enterprise_id,name) VALUES (95,'LS아이티씨');
INSERT INTO enterprise(enterprise_id,name) VALUES (96,'DB아이앤씨');
INSERT INTO enterprise(enterprise_id,name) VALUES (97,'포스코ICT');
INSERT INTO enterprise(enterprise_id,name) VALUES (98,'아시아나IDT');
INSERT INTO enterprise(enterprise_id,name) VALUES (99,'한진정보통신');
INSERT INTO enterprise(enterprise_id,name) VALUES (100,'티시스');
INSERT INTO enterprise(enterprise_id,name) VALUES (101,'GS ITM');
INSERT INTO enterprise(enterprise_id,name) VALUES (102,'메가존클라우드');
INSERT INTO enterprise(enterprise_id,name) VALUES (103,'베스핀글로벌');
INSERT INTO enterprise(enterprise_id,name) VALUES (104,'NDS');
INSERT INTO enterprise(enterprise_id,name) VALUES (105,'비즈테크파트너스');
INSERT INTO enterprise(enterprise_id,name) VALUES (106,'AKIS');
INSERT INTO enterprise(enterprise_id,name) VALUES (107,'쌍용정보통신');
INSERT INTO enterprise(enterprise_id,name) VALUES (108,'메타넷대우정보');
INSERT INTO enterprise(enterprise_id,name) VALUES (109,'동국시스템즈');
INSERT INTO enterprise(enterprise_id,name) VALUES (110,'동양시스템즈');
INSERT INTO enterprise(enterprise_id,name) VALUES (111,'넷마블(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (112,'(주)엔씨소프트');
INSERT INTO enterprise(enterprise_id,name) VALUES (113,'(주)우아한형제들');
INSERT INTO enterprise(enterprise_id,name) VALUES (114,'(주)넥슨코리아');
INSERT INTO enterprise(enterprise_id,name) VALUES (115,'엔에이치엔(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (116,'(주)크래프톤');
INSERT INTO enterprise(enterprise_id,name) VALUES (117,'(주)카카오엔터테인먼트');
INSERT INTO enterprise(enterprise_id,name) VALUES (118,'(주)지마켓');
INSERT INTO enterprise(enterprise_id,name) VALUES (119,'(주)카카오게임즈');
INSERT INTO enterprise(enterprise_id,name) VALUES (120,'(주)케이지이니시스');
INSERT INTO enterprise(enterprise_id,name) VALUES (121,'한국오라클(유)');
INSERT INTO enterprise(enterprise_id,name) VALUES (122,'(주)네오플');
INSERT INTO enterprise(enterprise_id,name) VALUES (123,'(주)더블유게임즈');
INSERT INTO enterprise(enterprise_id,name) VALUES (124,'(주)스마일게이트엔터테인먼트');
INSERT INTO enterprise(enterprise_id,name) VALUES (125,'한국아이비엠(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (126,'(주)컴투스');
INSERT INTO enterprise(enterprise_id,name) VALUES (127,'(유)시높시스코리아');
INSERT INTO enterprise(enterprise_id,name) VALUES (128,'(주)골프존');
INSERT INTO enterprise(enterprise_id,name) VALUES (129,'(주)더블다운인터액티브');
INSERT INTO enterprise(enterprise_id,name) VALUES (130,'(주)그라비티');
INSERT INTO enterprise(enterprise_id,name) VALUES (131,'(주)펄어비스');
INSERT INTO enterprise(enterprise_id,name) VALUES (132,'에스에이피코리아(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (133,'(주)한글과컴퓨터');
INSERT INTO enterprise(enterprise_id,name) VALUES (134,'라이엇게임즈코리아(유)');
INSERT INTO enterprise(enterprise_id,name) VALUES (135,'(주)지어소프트');
INSERT INTO enterprise(enterprise_id,name) VALUES (136,'데브시스터즈(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (137,'(주)코리아센터');
INSERT INTO enterprise(enterprise_id,name) VALUES (138,'(주)위메이드');
INSERT INTO enterprise(enterprise_id,name) VALUES (139,'유비벨록스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (140,'(주)다날');
INSERT INTO enterprise(enterprise_id,name) VALUES (141,'(주)웹젠');
INSERT INTO enterprise(enterprise_id,name) VALUES (142,'(주)아프리카티비');
INSERT INTO enterprise(enterprise_id,name) VALUES (143,'(주)네오위즈홀딩스');
INSERT INTO enterprise(enterprise_id,name) VALUES (144,'(주)네오위즈');
INSERT INTO enterprise(enterprise_id,name) VALUES (145,'(주)지니뮤직');
INSERT INTO enterprise(enterprise_id,name) VALUES (146,'(주)하이퍼커넥트');
INSERT INTO enterprise(enterprise_id,name) VALUES (147,'(주)위버스컴퍼니');
INSERT INTO enterprise(enterprise_id,name) VALUES (148,'(주)라이온하트스튜디오');
INSERT INTO enterprise(enterprise_id,name) VALUES (149,'제니스앤컴퍼니(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (150,'동국시스템즈(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (151,'에스케이엠앤서비스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (152,'팅크웨어(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (153,'(주)스마일게이트메가포트');
INSERT INTO enterprise(enterprise_id,name) VALUES (154,'(주)티머니');
INSERT INTO enterprise(enterprise_id,name) VALUES (155,'(주)에프에스엔');
INSERT INTO enterprise(enterprise_id,name) VALUES (156,'(주)비트망고');
INSERT INTO enterprise(enterprise_id,name) VALUES (157,'(주)사삼구구코리아');
INSERT INTO enterprise(enterprise_id,name) VALUES (158,'(주)안랩');
INSERT INTO enterprise(enterprise_id,name) VALUES (159,'리디(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (160,'(주)엔드림');
INSERT INTO enterprise(enterprise_id,name) VALUES (161,'(주)조이시티');
INSERT INTO enterprise(enterprise_id,name) VALUES (162,'젬텍(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (163,'코나아이(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (164,'(주)다나와');
INSERT INTO enterprise(enterprise_id,name) VALUES (165,'(주)아이비케이시스템');
INSERT INTO enterprise(enterprise_id,name) VALUES (166,'(주)드림시큐리티');
INSERT INTO enterprise(enterprise_id,name) VALUES (167,'다쏘시스템코리아(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (168,'(주)아이지에이웍스');
INSERT INTO enterprise(enterprise_id,name) VALUES (169,'(주)카카오브이엑스');
INSERT INTO enterprise(enterprise_id,name) VALUES (170,'네이버파이낸셜(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (171,'네이버클라우드(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (172,'라인플러스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (173,'아이피엑스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (174,'엔테크서비스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (175,'웍스모바일(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (176,'라인비즈플러스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (177,'(주)그린웹서비스');
INSERT INTO enterprise(enterprise_id,name) VALUES (178,'네이버제트(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (179,'라인게임즈(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (180,'라인파이낸셜플러스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (181,'스노우(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (182,'네이버랩스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (183,'삼성생명보험(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (184,'삼성물산(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (185,'삼성디스플레이(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (186,'삼성화재해상보험(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (187,'삼성에스디에스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (188,'삼성SDI(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (189,'삼성증권(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (190,'삼성증권(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (191,'삼성전기(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (192,'삼성엔지니어링(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (193,'삼성중공업(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (194,'삼성전자판매(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (195,'(주)호텔신라');
INSERT INTO enterprise(enterprise_id,name) VALUES (196,'삼성카드(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (197,'삼성전자로지텍(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (198,'삼성전자서비스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (199,'삼성바이오로직스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (200,'삼성바이오에피스(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (201,'에스티엠(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (202,'에이치디씨신라면세점(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (203,'삼성메디슨(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (204,'(주)멀티캠퍼스');
INSERT INTO enterprise(enterprise_id,name) VALUES (205,'삼성자산운용(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (206,'(주)삼우종합건축사사무소');
INSERT INTO enterprise(enterprise_id,name) VALUES (207,'(주)대한항공');
INSERT INTO enterprise(enterprise_id,name) VALUES (208,'(주)한진');
INSERT INTO enterprise(enterprise_id,name) VALUES (209,'(주)한진칼');
INSERT INTO enterprise(enterprise_id,name) VALUES (210,'한국공항(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (211,'(주)진에어');
INSERT INTO enterprise(enterprise_id,name) VALUES (212,'한진부산컨테이너터미널(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (213,'한진정보통신(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (214,'(주)칼호텔네트워크');
INSERT INTO enterprise(enterprise_id,name) VALUES (215,'(주)칼호텔네트워크');
INSERT INTO enterprise(enterprise_id,name) VALUES (216,'한진인천컨테이너터미널(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (217,'서울복합물류프로젝트금융투자(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (218,'정석기업(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (219,'(주)당근마켓');
INSERT INTO enterprise(enterprise_id,name) VALUES (220,'네오사피엔스');
INSERT INTO enterprise(enterprise_id,name) VALUES (221,'OK데이터시스템');
INSERT INTO enterprise(enterprise_id,name) VALUES (222,'(주)머큐리');
INSERT INTO enterprise(enterprise_id,name) VALUES (223,'(주)유라');
INSERT INTO enterprise(enterprise_id,name) VALUES (224,'(주)와일리');
INSERT INTO enterprise(enterprise_id,name) VALUES (225,'테크니컬러로키아 유한회사');
INSERT INTO enterprise(enterprise_id,name) VALUES (226,'인바디');
INSERT INTO enterprise(enterprise_id,name) VALUES (227,'주식회사 파수');
INSERT INTO enterprise(enterprise_id,name) VALUES (228,'(주)엘젠');
INSERT INTO enterprise(enterprise_id,name) VALUES (229,'마인즈랩');
INSERT INTO enterprise(enterprise_id,name) VALUES (230,'딥브루닷');
INSERT INTO enterprise(enterprise_id,name) VALUES (231,'(주)쥬비스다이어트');
INSERT INTO enterprise(enterprise_id,name) VALUES (232,'동양시스템(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (233,'아이와이씨엔씨(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (234,'로지스팟');
INSERT INTO enterprise(enterprise_id,name) VALUES (235,'코멘토');
INSERT INTO enterprise(enterprise_id,name) VALUES (236,'와이즈와이어즈');
INSERT INTO enterprise(enterprise_id,name) VALUES (237,'주식회사 쏘카');
INSERT INTO enterprise(enterprise_id,name) VALUES (238,'(주)플랜아이');
INSERT INTO enterprise(enterprise_id,name) VALUES (239,'일동이커머스');
INSERT INTO enterprise(enterprise_id,name) VALUES (240,'에스에스엠케이(주)');
INSERT INTO enterprise(enterprise_id,name) VALUES (241,'(주)이마트');
INSERT INTO enterprise(enterprise_id,name) VALUES (242,'(주)신세계');
INSERT INTO enterprise(enterprise_id,name) VALUES (243,'(주)신세계디에프');
INSERT INTO enterprise(enterprise_id,name) VALUES (244,'(주)에스씨케이컴퍼니');
INSERT INTO enterprise(enterprise_id,name) VALUES (245,'(주)이마트24');
INSERT INTO enterprise(enterprise_id,name) VALUES (246,'(주)에스에스지닷컴');
INSERT INTO enterprise(enterprise_id,name) VALUES (247,'(주)신세계인터내셔날');
INSERT INTO enterprise(enterprise_id,name) VALUES (248,'(주)조선호텔앤리조트');
INSERT INTO enterprise(enterprise_id,name) VALUES (249,'(주)신세계라이브쇼핑');
INSERT INTO enterprise(enterprise_id,name) VALUES (250,'해피해킹');
INSERT INTO enterprise(enterprise_id,name) VALUES (251,'삼성전자(주)');
insert into job values (1, "IT교육");
insert into job values (2, "게임개발");
insert into job values (3, "기술지원");
insert into job values (4, "데이터분석가");
insert into job values (5, "데이터엔지니어");
insert into job values (6, "백엔드/서버개발");
insert into job values (7, "보안관제");
insert into job values (8, "보안컨설팅");
insert into job values (9, "앱개발");
insert into job values (10, "웹개발");
insert into job values (11, "웹마스터");
insert into job values (12, "유지보수");
insert into job values (13, "정보보안");
insert into job values (14, "퍼블리셔");
insert into job values (15, "검색엔진");
insert into job values (16, "네트워크");
insert into job values (17, "데이터라벨링");
insert into job values (18, "데이터마이닝");
insert into job values (19, "데이터시각화");
insert into job values (20, "딥러닝");
insert into job values (21, "머신러닝");
insert into job values (22, "메타버스");
insert into job values (23, "모델링");
insert into job values (24, "모의해킹");
insert into job values (25, "미들웨어");
insert into job values (26, "반응형웹");
insert into job values (27, "방화벽");
insert into job values (28, "블록체인");
insert into job values (29, "빅데이터");
insert into job values (30, "프론트앤드");
insert into job values (31, "웹기획-PM");
insert into job values (32, "웹디자인");
insert into job values (33, "웹퍼블리셔");
insert into job values (34, "UI/UX 디자이너");
INSERT INTO campus(campus_id,city,class) VALUES (1,'서울',0);
INSERT INTO campus(campus_id,city,class) VALUES (2,'서울',1);
INSERT INTO campus(campus_id,city,class) VALUES (3,'서울',2);
INSERT INTO campus(campus_id,city,class) VALUES (4,'서울',3);
INSERT INTO campus(campus_id,city,class) VALUES (5,'서울',4);
INSERT INTO campus(campus_id,city,class) VALUES (6,'서울',5);
INSERT INTO campus(campus_id,city,class) VALUES (7,'서울',6);
INSERT INTO campus(campus_id,city,class) VALUES (8,'서울',7);
INSERT INTO campus(campus_id,city,class) VALUES (9,'서울',8);
INSERT INTO campus(campus_id,city,class) VALUES (10,'서울',9);
INSERT INTO campus(campus_id,city,class) VALUES (11,'서울',10);
INSERT INTO campus(campus_id,city,class) VALUES (12,'서울',11);
INSERT INTO campus(campus_id,city,class) VALUES (13,'서울',12);
INSERT INTO campus(campus_id,city,class) VALUES (14,'서울',13);
INSERT INTO campus(campus_id,city,class) VALUES (15,'서울',14);
INSERT INTO campus(campus_id,city,class) VALUES (16,'서울',15);
INSERT INTO campus(campus_id,city,class) VALUES (17,'서울',16);
INSERT INTO campus(campus_id,city,class) VALUES (18,'서울',17);
INSERT INTO campus(campus_id,city,class) VALUES (19,'서울',18);
INSERT INTO campus(campus_id,city,class) VALUES (20,'서울',19);
INSERT INTO campus(campus_id,city,class) VALUES (21,'서울',20);
INSERT INTO campus(campus_id,city,class) VALUES (22,'광주',0);
INSERT INTO campus(campus_id,city,class) VALUES (23,'광주',1);
INSERT INTO campus(campus_id,city,class) VALUES (24,'광주',2);
INSERT INTO campus(campus_id,city,class) VALUES (25,'광주',3);
INSERT INTO campus(campus_id,city,class) VALUES (26,'광주',4);
INSERT INTO campus(campus_id,city,class) VALUES (27,'광주',5);
INSERT INTO campus(campus_id,city,class) VALUES (28,'광주',6);
INSERT INTO campus(campus_id,city,class) VALUES (29,'부울경',0);
INSERT INTO campus(campus_id,city,class) VALUES (30,'부울경',1);
INSERT INTO campus(campus_id,city,class) VALUES (31,'부울경',2);
INSERT INTO campus(campus_id,city,class) VALUES (32,'부울경',3);
INSERT INTO campus(campus_id,city,class) VALUES (33,'부울경',4);
INSERT INTO campus(campus_id,city,class) VALUES (34,'부울경',5);
INSERT INTO campus(campus_id,city,class) VALUES (35,'대전',0);
INSERT INTO campus(campus_id,city,class) VALUES (36,'대전',1);
INSERT INTO campus(campus_id,city,class) VALUES (37,'대전',2);
INSERT INTO campus(campus_id,city,class) VALUES (38,'대전',3);
INSERT INTO campus(campus_id,city,class) VALUES (39,'대전',4);
INSERT INTO campus(campus_id,city,class) VALUES (40,'대전',5);
INSERT INTO campus(campus_id,city,class) VALUES (41,'대전',6);
INSERT INTO campus(campus_id,city,class) VALUES (42,'대전',7);
INSERT INTO campus(campus_id,city,class) VALUES (43,'대전',8);
INSERT INTO campus(campus_id,city,class) VALUES (44,'구미',0);
INSERT INTO campus(campus_id,city,class) VALUES (45,'구미',1);
INSERT INTO campus(campus_id,city,class) VALUES (46,'구미',2);
INSERT INTO campus(campus_id,city,class) VALUES (47,'구미',3);
INSERT INTO campus(campus_id,city,class) VALUES (48,'구미',4);
INSERT INTO campus(campus_id,city,class) VALUES (49,'구미',5);
INSERT INTO campus(campus_id,city,class) VALUES (50,'구미',6);