INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('지원 동기가 무엇인가요?', '인성', '공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('성격의 장점과 단점은 무엇이 있나요?', '인성', '공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('같이 일하고 싶은/싫은 스타일의 사람은 누구인가요?', '인성', '공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('인생에서 가장 열심히 했던 일이나 순간은 언제인가요?', '인성', '공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('간단한 자기소개 부탁드립니다.','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('저희 회사에 지원한 동기가 무엇인가요?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('자신의 능력 밖을 벗어난 업무가 주어진다면 어떻게 하겠습니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('입사 후 포부가 무엇입니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('당신에게 일이 왜 중요합니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('직장은 어떤 면을 보고 선택합니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('인생에서 가장 필요한 사항은 무엇이라 생각하나요?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('본인이 리더로 추진했던 일이 있습니까? 있다면 어떤 성과가 나왔는지 말해보세요.','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('회사 근무를 하면서 가장 중요하다고 생각하는 것은 무엇입니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('본인은 따라가는 스타일입니까, 아니면 주도하는 스타일입니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('자신의 능력 밖을 벗어난 업무가 주어진다면 어떻게 하겠습니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('어떤 일에 적극적으로 임한 순간은 언제였습니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('어떤 경영 스타일일때 자신의 능력이 최대가 되나요?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('상사의 말이 확실히 틀렸을 때는 어떻게 할 것인가','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('입사 후 회사와 맞지 않는다면 어떻게 하시겠습니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('어떤 상황에서 스트레스를 받나요?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('본인의 업무스타일은 어떤 유형인가요?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('상사와 의견이 다를 때는 어떻게 대처할 것입니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('상사가 부당한 업무지시를 시킨다면 어떻게 할 것입니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('노래방에서 몇 시간이나 놀 수 있습니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('단체활동에서 의견 충돌이 일어날 경우 어떻게 해결하겠습니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('대인관계에서 가장 중요하게 생각하는 것은 무엇입니까?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('하고싶지 않았던 부서에 배정되도 괜찮은가?','인성','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('인생에서 가장 행복했던 경험이 무엇인가요?','인성','공통');

INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('트러블 슈팅 경험이 있으신가요?', '직무', '공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('어떤 언어를 가장 많이 사용하시나요? 그 이유는?', '직무', '공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('좋은 소프트웨어란 무엇이라고 생각하나요?', '직무', '공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('어떤 개발자가 되고 싶으신가요?', '직무', '공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('지금까지 어떤 프로젝트를 해보셨나요?','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('전에 진행했던 프로젝트의 아키텍처를 설명해 보세요.','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('자신이 제출한 포트폴리오를 설명해 보세요.','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('사용할 줄 아는 프로그래밍 언어는 어떤 것들이 있으며 얼마나 하나요?','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('큐에대해 설명해 보세요.','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('본인이 사용할 줄 아는 언어들의 차이점은 무엇인가요?','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('프로세스와 스레드의 차이점은 무엇인가요?','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('본인이 지원한 직무가 무슨 일을 한다고 생각하나요?','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('업데이트한 내용에 큰 문제가 생겼다면 어떻게 할 것인가?','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('http와 https의 차이에 대해서 설명해보세요.','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('GET방식과 POST방식의 차이에 대하여 설명하세요.','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('컴포넌트와 모듈의 차이를 설명해보세요','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('객체 지향과 절차지향의 차이점을 설명해 보세요.','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('객체지향 언어의 특징을 설명해보세요.','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('오버라이딩 오버로딩의 차이점과 특징에대해 설명해 보세요.','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('교육 프로그램에 참가하게 된 계기가 무엇인가요?','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('어떤 서비스를 개발하고 싶은가요?','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('회사 기술 스택에 맞추어 단기간 내에 언어와 프레임워크를 학습해야 할 때, 어떻게 공부하고 해결할 것인가?','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('개발에 관심을 가지게 된 계기가 무엇인가요?','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('비IT 동료와 효과적으로 의사소통하려면 어떻게 해야 합니까? ','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('트러블슈팅을 해본적이 있나요?','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('Stack 과 Queue에대해 설명해주세요.','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('좋은 코드란 무엇이라 생각하시나요?','직무','공통');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('개발 능력 향상을 위해 어떤 것을 하고 계신가요?' ,'직무', '공통');


INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('추상화에 대해 설명해주세요.', '직무', 'Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('MVC패턴에 대해 설명해주세요', '직무', 'Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('세션과 쿠키의 차이점에대해 설명해주세요.', '직무', 'Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('Spring DI에 대해 설명해주세요.', '직무', 'Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('ORM에 대해 설명해 보세요','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('데이터베이스 옵티마이저에 대해 설명해주세요','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('JPA를 사용하면 좋은점이 무엇인가요?','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('JWT에 대해 설명해주세요, 사용하면 장점과 단점?','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('Enum 사용해보셨나요? Enum이란 무엇인가요?','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('REST API란? REST API 명령어(CRUD) 아시는것 설명해주세요.','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('세션과 쿠키의 차이점을 설명해보세요.','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('HTTP METHOD에 대해 설명해보세요','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('HTTP 상태코드에 대해 아는대로 말해보세요.','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('DB에서 인덱스를 사용했을때 장점이 무엇이있나요?','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('가비지 컬렉션에대해 설명해보세요.','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('브라우저 렌더링 과정을 설명해주세요.','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('CORS는 무엇인지, 이를 처리해본 경험이 있다면 말씀해주세요.','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('타입스크립트를 사용하는 이유는 무엇인가요?','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('브라우저는 어떻게 동작하는지 설명해주세요.','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('스프링프레임워크에대해 설명해보세요.','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('RDBMS와 NOSQL의 차이에대해 설명해보세요.','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('MyBatis의 장점에대해 설명해보세요.','직무','Backend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('싱글톤 패턴에 대해 설명해주세요','직무','Backend');

INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('GET,POST를 어떻게 다르게 쓰는지 말씀해 주세요.', '직무', 'Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('호이스팅에 대해서 설명해보세요.', '직무', 'Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('this의 용법 아는대로 설명해주세요.', '직무', 'Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('SPA에대해 설명해 주세요.', '직무', 'Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('var let const 의 차이점에대해 설명해주세요.', '직무', 'Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('Promise와 Callback의 차이를 설명해주세요.','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('async, await 사용방법을 설명해주세요.','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('함수 선언형과 함수 표현식의 차이에 대해 설명해주세요.','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('자바스크립트가 유동적인 언어인 이유는 무엇인가요?','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('CSS에서 margin과 padding에 대해 설명해주세요.','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('브라우저 저장소에는 무엇이 있고 그것들의 차이점을 설명해주세요.','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('이벤트 버블링에 대해서 말씀해 주세요.','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('SASS, SCSS를 사용해본적이 있나요? 기존 CSS와 비교할 때 어떤면이 더 좋은가요?','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('Vue와 React의 차이는 무엇인가요?','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('Vue에서 양방향 데이터가 일어나는 원리에 대해서 설명해주세요.','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('MVVM모델에 대해서 설명해주세요.','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('ES6에서 Arrow 함수를 언제 쓰나요?','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('Javascript에서 this란 무엇인가요?','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('Frond-End 성능 최적화란 무엇인가요? 성능 최적화 경험이 있다면 설명해 주세요.','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('CSR과 SSR의 차이점은 무엇인가요?','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('주소창에 naver.com을 입력하면 어떤 일이 생기나요?','직무','Frontend');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('AJAX에대해 설명해보세요.','직무','Frontend');

INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('리플렉션이란 무엇인가요?', '직무', 'Android/iOS');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('constraint layout에대해 설명해주세요.', '직무', 'Android/iOS');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('액티비티와 프래그먼트에 대해 설명해주세요.', '직무', 'Android/iOS');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('안드로이드 빌드 프로세스에대해 설명해주세요.', '직무', 'Android/iOS');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('Bounds 와 Frame 의 차이점을 설명해주세요.', '직무', 'Android/iOS');

INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('고유값(eigen value)와 고유벡터(eigen vector)에 대해 설명해주세요. 그리고 왜 중요할까요?', '직무', 'Data Scientist');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('확률 모형과 확률 변수는 무엇일까요?', '직무', 'Data Scientist');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('좋은 feature란 무엇인가요. 이 feature의 성능을 판단하기 위한 방법에는 어떤 것이 있나요?', '직무', 'Data Scientist');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('상관관계는 인과관계를 의미하지 않는다”라는 말이 있습니다. 설명해주실 수 있나요?', '직무', 'Data Scientist');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('나만의 feature selection 방식을 설명해봅시다.', '직무', 'Data Scientist');

INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('DevOps를 설명해주세요..', '직무', 'DevOps');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('DevOps 구현을위한 모범 사례는 무엇인가요?', '직무', 'DevOps');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('DevOps의 주요 구성 요소는 무엇입니까?', '직무', 'DevOps');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('지속적인 통합을 설명해주세요.', '직무', 'DevOps');
INSERT INTO interview_question(question, question_type, question_detail_type) VALUES ('프로젝트에서 DevOps를 구현해야 할 때 어떻게 접근 하시겠습니까?', '직무', 'DevOps');




INSERT INTO enterprise(name) VALUES ('네이버(주)');
INSERT INTO enterprise(name) VALUES ('카카오(주)');
INSERT INTO enterprise(name) VALUES ('(주)다우기술');
INSERT INTO enterprise(name) VALUES ('(주)빗썸홀딩스');
INSERT INTO enterprise(name) VALUES ('(주)케이티씨에스');
INSERT INTO enterprise(name) VALUES ('메가존(주)');
INSERT INTO enterprise(name) VALUES ('네이버클라우드(주)');
INSERT INTO enterprise(name) VALUES ('라인플러스(주)');
INSERT INTO enterprise(name) VALUES ('엔에이치엔한국사이버결제(주)');
INSERT INTO enterprise(name) VALUES ('(주)카카오모빌리티');
INSERT INTO enterprise(name) VALUES ('나이스평가정보(주)');
INSERT INTO enterprise(name) VALUES ('(주)야놀자');
INSERT INTO enterprise(name) VALUES ('(주)코스콤');
INSERT INTO enterprise(name) VALUES ('네이버웹툰(유)');
INSERT INTO enterprise(name) VALUES ('(주)케이지모빌리언스');
INSERT INTO enterprise(name) VALUES ('구글코리아(유)');
INSERT INTO enterprise(name) VALUES ('(주)연합뉴스');
INSERT INTO enterprise(name) VALUES ('이데일리(주)');
INSERT INTO enterprise(name) VALUES ('(주)여기어때컴퍼니');
INSERT INTO enterprise(name) VALUES ('카페24(주)');
INSERT INTO enterprise(name) VALUES ('(주)드림어스컴퍼니');
INSERT INTO enterprise(name) VALUES ('(주)헥토이노베이션');
INSERT INTO enterprise(name) VALUES ('(주)가비아');
INSERT INTO enterprise(name) VALUES ('한국인터넷진흥원');
INSERT INTO enterprise(name) VALUES ('(주)브랜드엑스코퍼레이션');
INSERT INTO enterprise(name) VALUES ('(주)이엔코퍼레이션');
INSERT INTO enterprise(name) VALUES ('(주)와이지플러스');
INSERT INTO enterprise(name) VALUES ('(주)이머니');
INSERT INTO enterprise(name) VALUES ('인포뱅크(주)');
INSERT INTO enterprise(name) VALUES ('(주)에스비에스에이앤티');
INSERT INTO enterprise(name) VALUES ('(주)사람인에이치알');
INSERT INTO enterprise(name) VALUES ('한일네트웍스(주)');
INSERT INTO enterprise(name) VALUES ('(주)키다리스튜디오');
INSERT INTO enterprise(name) VALUES ('한국평가데이터(주)');
INSERT INTO enterprise(name) VALUES ('(주)헥토파이낸셜');
INSERT INTO enterprise(name) VALUES ('(주)알스퀘어');
INSERT INTO enterprise(name) VALUES ('블룸버그코리아(유)');
INSERT INTO enterprise(name) VALUES ('(주)더플랜코퍼레이션');
INSERT INTO enterprise(name) VALUES ('(주)천재교육');
INSERT INTO enterprise(name) VALUES ('GS건설(주)');
INSERT INTO enterprise(name) VALUES ('유빈스(주)');
INSERT INTO enterprise(name) VALUES ('(주)예가람저축은행');
INSERT INTO enterprise(name) VALUES ('(주)코리아써키트');
INSERT INTO enterprise(name) VALUES ('(주)하나금융티아이');
INSERT INTO enterprise(name) VALUES ('현대건설');
INSERT INTO enterprise(name) VALUES ('(주)현대홈쇼핑');
INSERT INTO enterprise(name) VALUES ('롯데캐피탈(주)');
INSERT INTO enterprise(name) VALUES ('KB생명보험(주)');
INSERT INTO enterprise(name) VALUES ('제일약품');
INSERT INTO enterprise(name) VALUES ('현대오토에버(주)');
INSERT INTO enterprise(name) VALUES ('금호건설(주)');
INSERT INTO enterprise(name) VALUES ('한국투자증권(주)');
INSERT INTO enterprise(name) VALUES ('대상정보기술(주)');
INSERT INTO enterprise(name) VALUES ('GS네오텍(주)');
INSERT INTO enterprise(name) VALUES ('(주)플그림');
INSERT INTO enterprise(name) VALUES ('쿠팡 주식회사');
INSERT INTO enterprise(name) VALUES ('롯데멤버스(주)');
INSERT INTO enterprise(name) VALUES ('브이피(주)');
INSERT INTO enterprise(name) VALUES ('플레이디');
INSERT INTO enterprise(name) VALUES ('한화테크윈(주)');
INSERT INTO enterprise(name) VALUES ('삼성물산');
INSERT INTO enterprise(name) VALUES ('(주)LF');
INSERT INTO enterprise(name) VALUES ('(주)신세계아이앤씨');
INSERT INTO enterprise(name) VALUES ('(주)포스코');
INSERT INTO enterprise(name) VALUES ('교보핫트랙스(주)');
INSERT INTO enterprise(name) VALUES ('현대자동차(주)');
INSERT INTO enterprise(name) VALUES ('(주)한샘');
INSERT INTO enterprise(name) VALUES ('SM그룹');
INSERT INTO enterprise(name) VALUES ('엠코테크놀로지');
INSERT INTO enterprise(name) VALUES ('우리은행-우리에프아이에스');
INSERT INTO enterprise(name) VALUES ('기업은행');
INSERT INTO enterprise(name) VALUES ('KEB하나은행');
INSERT INTO enterprise(name) VALUES ('SC제일은행');
INSERT INTO enterprise(name) VALUES ('KB국민은행-KB데이터시스템');
INSERT INTO enterprise(name) VALUES ('신한은행-신한DS');
INSERT INTO enterprise(name) VALUES ('외환은행');
INSERT INTO enterprise(name) VALUES ('한국시티은행');
INSERT INTO enterprise(name) VALUES ('외환은행');
INSERT INTO enterprise(name) VALUES ('카카오엔터프라이즈');
INSERT INTO enterprise(name) VALUES ('LG CNS');
INSERT INTO enterprise(name) VALUES ('삼성SDS');
INSERT INTO enterprise(name) VALUES ('두산디지털이노베이션');
INSERT INTO enterprise(name) VALUES ('SK C&C');
INSERT INTO enterprise(name) VALUES ('CJ올리브네트웍스');
INSERT INTO enterprise(name) VALUES ('티맥스소프트');
INSERT INTO enterprise(name) VALUES ('현대IT&E');
INSERT INTO enterprise(name) VALUES ('현대HDS');
INSERT INTO enterprise(name) VALUES ('농협정보시스템');
INSERT INTO enterprise(name) VALUES ('미라콤아이앤씨');
INSERT INTO enterprise(name) VALUES ('IBK시스템');
INSERT INTO enterprise(name) VALUES ('코오롱베니트');
INSERT INTO enterprise(name) VALUES ('한화시스템/ICT');
INSERT INTO enterprise(name) VALUES ('교보정보통신');
INSERT INTO enterprise(name) VALUES ('KT DS');
INSERT INTO enterprise(name) VALUES ('LS아이티씨');
INSERT INTO enterprise(name) VALUES ('DB아이앤씨');
INSERT INTO enterprise(name) VALUES ('포스코ICT');
INSERT INTO enterprise(name) VALUES ('아시아나IDT');
INSERT INTO enterprise(name) VALUES ('한진정보통신');
INSERT INTO enterprise(name) VALUES ('티시스');
INSERT INTO enterprise(name) VALUES ('GS ITM');
INSERT INTO enterprise(name) VALUES ('메가존클라우드');
INSERT INTO enterprise(name) VALUES ('베스핀글로벌');
INSERT INTO enterprise(name) VALUES ('NDS');
INSERT INTO enterprise(name) VALUES ('비즈테크파트너스');
INSERT INTO enterprise(name) VALUES ('AKIS');
INSERT INTO enterprise(name) VALUES ('쌍용정보통신');
INSERT INTO enterprise(name) VALUES ('메타넷대우정보');
INSERT INTO enterprise(name) VALUES ('동국시스템즈');
INSERT INTO enterprise(name) VALUES ('동양시스템즈');
INSERT INTO enterprise(name) VALUES ('넷마블(주)');
INSERT INTO enterprise(name) VALUES ('(주)엔씨소프트');
INSERT INTO enterprise(name) VALUES ('(주)우아한형제들');
INSERT INTO enterprise(name) VALUES ('(주)넥슨코리아');
INSERT INTO enterprise(name) VALUES ('엔에이치엔(주)');
INSERT INTO enterprise(name) VALUES ('(주)크래프톤');
INSERT INTO enterprise(name) VALUES ('(주)카카오엔터테인먼트');
INSERT INTO enterprise(name) VALUES ('(주)지마켓');
INSERT INTO enterprise(name) VALUES ('(주)카카오게임즈');
INSERT INTO enterprise(name) VALUES ('(주)케이지이니시스');
INSERT INTO enterprise(name) VALUES ('한국오라클(유)');
INSERT INTO enterprise(name) VALUES ('(주)네오플');
INSERT INTO enterprise(name) VALUES ('(주)더블유게임즈');
INSERT INTO enterprise(name) VALUES ('(주)스마일게이트엔터테인먼트');
INSERT INTO enterprise(name) VALUES ('한국아이비엠(주)');
INSERT INTO enterprise(name) VALUES ('(주)컴투스');
INSERT INTO enterprise(name) VALUES ('(유)시높시스코리아');
INSERT INTO enterprise(name) VALUES ('(주)골프존');
INSERT INTO enterprise(name) VALUES ('(주)더블다운인터액티브');
INSERT INTO enterprise(name) VALUES ('(주)그라비티');
INSERT INTO enterprise(name) VALUES ('(주)펄어비스');
INSERT INTO enterprise(name) VALUES ('에스에이피코리아(주)');
INSERT INTO enterprise(name) VALUES ('(주)한글과컴퓨터');
INSERT INTO enterprise(name) VALUES ('라이엇게임즈코리아(유)');
INSERT INTO enterprise(name) VALUES ('(주)지어소프트');
INSERT INTO enterprise(name) VALUES ('데브시스터즈(주)');
INSERT INTO enterprise(name) VALUES ('(주)코리아센터');
INSERT INTO enterprise(name) VALUES ('(주)위메이드');
INSERT INTO enterprise(name) VALUES ('유비벨록스(주)');
INSERT INTO enterprise(name) VALUES ('(주)다날');
INSERT INTO enterprise(name) VALUES ('(주)웹젠');
INSERT INTO enterprise(name) VALUES ('(주)아프리카티비');
INSERT INTO enterprise(name) VALUES ('(주)네오위즈홀딩스');
INSERT INTO enterprise(name) VALUES ('(주)네오위즈');
INSERT INTO enterprise(name) VALUES ('(주)지니뮤직');
INSERT INTO enterprise(name) VALUES ('(주)하이퍼커넥트');
INSERT INTO enterprise(name) VALUES ('(주)위버스컴퍼니');
INSERT INTO enterprise(name) VALUES ('(주)라이온하트스튜디오');
INSERT INTO enterprise(name) VALUES ('제니스앤컴퍼니(주)');
INSERT INTO enterprise(name) VALUES ('동국시스템즈(주)');
INSERT INTO enterprise(name) VALUES ('에스케이엠앤서비스(주)');
INSERT INTO enterprise(name) VALUES ('팅크웨어(주)');
INSERT INTO enterprise(name) VALUES ('(주)스마일게이트메가포트');
INSERT INTO enterprise(name) VALUES ('(주)티머니');
INSERT INTO enterprise(name) VALUES ('(주)에프에스엔');
INSERT INTO enterprise(name) VALUES ('(주)비트망고');
INSERT INTO enterprise(name) VALUES ('(주)사삼구구코리아');
INSERT INTO enterprise(name) VALUES ('(주)안랩');
INSERT INTO enterprise(name) VALUES ('리디(주)');
INSERT INTO enterprise(name) VALUES ('(주)엔드림');
INSERT INTO enterprise(name) VALUES ('(주)조이시티');
INSERT INTO enterprise(name) VALUES ('젬텍(주)');
INSERT INTO enterprise(name) VALUES ('코나아이(주)');
INSERT INTO enterprise(name) VALUES ('(주)다나와');
INSERT INTO enterprise(name) VALUES ('(주)아이비케이시스템');
INSERT INTO enterprise(name) VALUES ('(주)드림시큐리티');
INSERT INTO enterprise(name) VALUES ('다쏘시스템코리아(주)');
INSERT INTO enterprise(name) VALUES ('(주)아이지에이웍스');
INSERT INTO enterprise(name) VALUES ('(주)카카오브이엑스');
INSERT INTO enterprise(name) VALUES ('네이버파이낸셜(주)');
INSERT INTO enterprise(name) VALUES ('네이버클라우드(주)');
INSERT INTO enterprise(name) VALUES ('라인플러스(주)');
INSERT INTO enterprise(name) VALUES ('아이피엑스(주)');
INSERT INTO enterprise(name) VALUES ('엔테크서비스(주)');
INSERT INTO enterprise(name) VALUES ('웍스모바일(주)');
INSERT INTO enterprise(name) VALUES ('라인비즈플러스(주)');
INSERT INTO enterprise(name) VALUES ('(주)그린웹서비스');
INSERT INTO enterprise(name) VALUES ('네이버제트(주)');
INSERT INTO enterprise(name) VALUES ('라인게임즈(주)');
INSERT INTO enterprise(name) VALUES ('라인파이낸셜플러스(주)');
INSERT INTO enterprise(name) VALUES ('스노우(주)');
INSERT INTO enterprise(name) VALUES ('네이버랩스(주)');
INSERT INTO enterprise(name) VALUES ('삼성생명보험(주)');
INSERT INTO enterprise(name) VALUES ('삼성물산(주)');
INSERT INTO enterprise(name) VALUES ('삼성디스플레이(주)');
INSERT INTO enterprise(name) VALUES ('삼성화재해상보험(주)');
INSERT INTO enterprise(name) VALUES ('삼성에스디에스(주)');
INSERT INTO enterprise(name) VALUES ('삼성SDI(주)');
INSERT INTO enterprise(name) VALUES ('삼성증권(주)');
INSERT INTO enterprise(name) VALUES ('삼성증권(주)');
INSERT INTO enterprise(name) VALUES ('삼성전기(주)');
INSERT INTO enterprise(name) VALUES ('삼성엔지니어링(주)');
INSERT INTO enterprise(name) VALUES ('삼성중공업(주)');
INSERT INTO enterprise(name) VALUES ('삼성전자판매(주)');
INSERT INTO enterprise(name) VALUES ('(주)호텔신라');
INSERT INTO enterprise(name) VALUES ('삼성카드(주)');
INSERT INTO enterprise(name) VALUES ('삼성전자로지텍(주)');
INSERT INTO enterprise(name) VALUES ('삼성전자서비스(주)');
INSERT INTO enterprise(name) VALUES ('삼성바이오로직스(주)');
INSERT INTO enterprise(name) VALUES ('삼성바이오에피스(주)');
INSERT INTO enterprise(name) VALUES ('에스티엠(주)');
INSERT INTO enterprise(name) VALUES ('에이치디씨신라면세점(주)');
INSERT INTO enterprise(name) VALUES ('삼성메디슨(주)');
INSERT INTO enterprise(name) VALUES ('(주)멀티캠퍼스');
INSERT INTO enterprise(name) VALUES ('삼성자산운용(주)');
INSERT INTO enterprise(name) VALUES ('(주)삼우종합건축사사무소');
INSERT INTO enterprise(name) VALUES ('(주)대한항공');
INSERT INTO enterprise(name) VALUES ('(주)한진');
INSERT INTO enterprise(name) VALUES ('(주)한진칼');
INSERT INTO enterprise(name) VALUES ('한국공항(주)');
INSERT INTO enterprise(name) VALUES ('(주)진에어');
INSERT INTO enterprise(name) VALUES ('한진부산컨테이너터미널(주)');
INSERT INTO enterprise(name) VALUES ('한진정보통신(주)');
INSERT INTO enterprise(name) VALUES ('(주)칼호텔네트워크');
INSERT INTO enterprise(name) VALUES ('(주)칼호텔네트워크');
INSERT INTO enterprise(name) VALUES ('한진인천컨테이너터미널(주)');
INSERT INTO enterprise(name) VALUES ('서울복합물류프로젝트금융투자(주)');
INSERT INTO enterprise(name) VALUES ('정석기업(주)');
INSERT INTO enterprise(name) VALUES ('(주)당근마켓');
INSERT INTO enterprise(name) VALUES ('네오사피엔스');
INSERT INTO enterprise(name) VALUES ('OK데이터시스템');
INSERT INTO enterprise(name) VALUES ('(주)머큐리');
INSERT INTO enterprise(name) VALUES ('(주)유라');
INSERT INTO enterprise(name) VALUES ('(주)와일리');
INSERT INTO enterprise(name) VALUES ('테크니컬러로키아 유한회사');
INSERT INTO enterprise(name) VALUES ('인바디');
INSERT INTO enterprise(name) VALUES ('주식회사 파수');
INSERT INTO enterprise(name) VALUES ('(주)엘젠');
INSERT INTO enterprise(name) VALUES ('마인즈랩');
INSERT INTO enterprise(name) VALUES ('딥브루닷');
INSERT INTO enterprise(name) VALUES ('(주)쥬비스다이어트');
INSERT INTO enterprise(name) VALUES ('동양시스템(주)');
INSERT INTO enterprise(name) VALUES ('아이와이씨엔씨(주)');
INSERT INTO enterprise(name) VALUES ('로지스팟');
INSERT INTO enterprise(name) VALUES ('코멘토');
INSERT INTO enterprise(name) VALUES ('와이즈와이어즈');
INSERT INTO enterprise(name) VALUES ('주식회사 쏘카');
INSERT INTO enterprise(name) VALUES ('(주)플랜아이');
INSERT INTO enterprise(name) VALUES ('일동이커머스');
INSERT INTO enterprise(name) VALUES ('에스에스엠케이(주)');
INSERT INTO enterprise(name) VALUES ('(주)이마트');
INSERT INTO enterprise(name) VALUES ('(주)신세계');
INSERT INTO enterprise(name) VALUES ('(주)신세계디에프');
INSERT INTO enterprise(name) VALUES ('(주)에스씨케이컴퍼니');
INSERT INTO enterprise(name) VALUES ('(주)이마트24');
INSERT INTO enterprise(name) VALUES ('(주)에스에스지닷컴');
INSERT INTO enterprise(name) VALUES ('(주)신세계인터내셔날');
INSERT INTO enterprise(name) VALUES ('(주)조선호텔앤리조트');
INSERT INTO enterprise(name) VALUES ('(주)신세계라이브쇼핑');
INSERT INTO enterprise(name) VALUES ('해피해킹');
INSERT INTO enterprise(name) VALUES ('삼성전자(주)');
INSERT INTO job(name) VALUES ('IT교육');
INSERT INTO job(name) VALUES ('게임개발');
INSERT INTO job(name) VALUES ('기술지원');
INSERT INTO job(name) VALUES ('데이터분석가');
INSERT INTO job(name) VALUES ('데이터엔지니어');
INSERT INTO job(name) VALUES ('백엔드/서버개발');
INSERT INTO job(name) VALUES ('보안관제');
INSERT INTO job(name) VALUES ('보안컨설팅');
INSERT INTO job(name) VALUES ('앱개발');
INSERT INTO job(name) VALUES ('웹개발');
INSERT INTO job(name) VALUES ('웹마스터');
INSERT INTO job(name) VALUES ('유지보수');
INSERT INTO job(name) VALUES ('정보보안');
INSERT INTO job(name) VALUES ('퍼블리셔');
INSERT INTO job(name) VALUES ('검색엔진');
INSERT INTO job(name) VALUES ('네트워크');
INSERT INTO job(name) VALUES ('데이터라벨링');
INSERT INTO job(name) VALUES ('데이터마이닝');
INSERT INTO job(name) VALUES ('데이터시각화');
INSERT INTO job(name) VALUES ('딥러닝');
INSERT INTO job(name) VALUES ('머신러닝');
INSERT INTO job(name) VALUES ('메타버스');
INSERT INTO job(name) VALUES ('모델링');
INSERT INTO job(name) VALUES ('모의해킹');
INSERT INTO job(name) VALUES ('미들웨어');
INSERT INTO job(name) VALUES ('반응형웹');
INSERT INTO job(name) VALUES ('방화벽');
INSERT INTO job(name) VALUES ('블록체인');
INSERT INTO job(name) VALUES ('빅데이터');
INSERT INTO job(name) VALUES ('프론트앤드');
INSERT INTO job(name) VALUES ('웹기획-PM');
INSERT INTO job(name) VALUES ('웹디자인');
INSERT INTO job(name) VALUES ('웹퍼블리셔');
INSERT INTO job(name) VALUES ('UI/UX 디자이너');
INSERT INTO campus(city,class) VALUES ('서울',null);
INSERT INTO campus(city,class) VALUES ('서울',1);
INSERT INTO campus(city,class) VALUES ('서울',2);
INSERT INTO campus(city,class) VALUES ('서울',3);
INSERT INTO campus(city,class) VALUES ('서울',4);
INSERT INTO campus(city,class) VALUES ('서울',5);
INSERT INTO campus(city,class) VALUES ('서울',6);
INSERT INTO campus(city,class) VALUES ('서울',7);
INSERT INTO campus(city,class) VALUES ('서울',8);
INSERT INTO campus(city,class) VALUES ('서울',9);
INSERT INTO campus(city,class) VALUES ('서울',10);
INSERT INTO campus(city,class) VALUES ('서울',11);
INSERT INTO campus(city,class) VALUES ('서울',12);
INSERT INTO campus(city,class) VALUES ('서울',13);
INSERT INTO campus(city,class) VALUES ('서울',14);
INSERT INTO campus(city,class) VALUES ('서울',15);
INSERT INTO campus(city,class) VALUES ('서울',16);
INSERT INTO campus(city,class) VALUES ('서울',17);
INSERT INTO campus(city,class) VALUES ('서울',18);
INSERT INTO campus(city,class) VALUES ('서울',19);
INSERT INTO campus(city,class) VALUES ('서울',20);
INSERT INTO campus(city,class) VALUES ('광주',null);
INSERT INTO campus(city,class) VALUES ('광주',1);
INSERT INTO campus(city,class) VALUES ('광주',2);
INSERT INTO campus(city,class) VALUES ('광주',3);
INSERT INTO campus(city,class) VALUES ('광주',4);
INSERT INTO campus(city,class) VALUES ('광주',5);
INSERT INTO campus(city,class) VALUES ('광주',6);
INSERT INTO campus(city,class) VALUES ('부울경',null);
INSERT INTO campus(city,class) VALUES ('부울경',1);
INSERT INTO campus(city,class) VALUES ('부울경',2);
INSERT INTO campus(city,class) VALUES ('부울경',3);
INSERT INTO campus(city,class) VALUES ('부울경',4);
INSERT INTO campus(city,class) VALUES ('부울경',5);
INSERT INTO campus(city,class) VALUES ('대전',null);
INSERT INTO campus(city,class) VALUES ('대전',1);
INSERT INTO campus(city,class) VALUES ('대전',2);
INSERT INTO campus(city,class) VALUES ('대전',3);
INSERT INTO campus(city,class) VALUES ('대전',4);
INSERT INTO campus(city,class) VALUES ('대전',5);
INSERT INTO campus(city,class) VALUES ('대전',6);
INSERT INTO campus(city,class) VALUES ('대전',7);
INSERT INTO campus(city,class) VALUES ('대전',8);
INSERT INTO campus(city,class) VALUES ('구미',null);
INSERT INTO campus(city,class) VALUES ('구미',1);
INSERT INTO campus(city,class) VALUES ('구미',2);
INSERT INTO campus(city,class) VALUES ('구미',3);
INSERT INTO campus(city,class) VALUES ('구미',4);
INSERT INTO campus(city,class) VALUES ('구미',5);
INSERT INTO campus(city,class) VALUES ('구미',6);
